---
- name: Configurar mi laboratorio DevOps desde cero
  hosts: servidores_ubuntu
  become: true

  tasks:
    - name: Actualizar el sistema (apt update)
      ansible.builtin.apt: # <--- FQCN
        update_cache: true
        upgrade: dist

    - name: Instalar dependencias básicas
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - git
        state: present

    - name: Descargar script de instalación de Docker
      ansible.builtin.get_url: # <--- Usamos el módulo correcto en vez de curl
        url: https://get.docker.com
        dest: /tmp/get-docker.sh
        mode: '0755'

    - name: Ejecutar script de Docker
      ansible.builtin.shell: |
        set -o pipefail
        /tmp/get-docker.sh
      args:
        executable: /bin/bash
        creates: /usr/bin/docker
      register: docker_install # Para que el linter sepa que rastreamos el resultado

    - name: Asegurar que el usuario pueda usar Docker sin sudo
      ansible.builtin.user: # <--- FQCN
        name: "{{ ansible_user }}"
        groups: docker
        append: true

    - name: Clonar mi repositorio de prácticas
      ansible.builtin.git: # <--- FQCN
        repo: 'https://github.com/wlabra/devopspractice.git'
        dest: "/home/{{ ansible_user }}/devopspractice"
        version: main # Especificar la rama ayuda a la idempotencia
        force: true
        accept_hostkey: true
      become: true
      become_user: "{{ ansible_user }}"

    - name: Asegurar que el dueño de la carpeta sea el usuario correcto
      ansible.builtin.file:
        path: "/home/{{ ansible_user }}/devopspractice"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        recurse: true
      become: true
      environment:
        GIT_TERMINAL_PROMPT: 0
