---
- name: Configurar mi laboratorio DevOps desde cero
  hosts: servidores_ubuntu
  become: true

  tasks:
    - name: Eliminar carpeta antigua para evitar conflictos
      ansible.builtin.file:
        path: "/home/{{ ansible_user }}/mi-primera-app"
        state: absent

    - name: Actualizar el sistema (apt update)
      ansible.builtin.apt:
        update_cache: true
        upgrade: dist

    - name: Instalar dependencias básicas
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - git
          - python3-pip
          - python3-docker # Necesario para que Ansible hable con Docker
        state: present

    - name: Descargar script de instalación de Docker
      ansible.builtin.get_url:
        url: https://get.docker.com
        dest: /tmp/get-docker.sh
        mode: '0755'

    - name: Ejecutar script de Docker
      ansible.builtin.shell: |
        set -o pipefail
        /tmp/get-docker.sh
      args:
        executable: /bin/bash
        creates: /usr/bin/docker

    - name: Asegurar que el usuario pueda usar Docker sin sudo
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: docker
        append: true

    - name: Corregir propiedad de la carpeta destino (Pre-vuelo)
      ansible.builtin.file:
        path: "/home/{{ ansible_user }}/devopspractice"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        state: directory
        recurse: yes
      failed_when: false # Si la carpeta no existe aún, que no falle

    - name: Clonar mi repositorio de prácticas
      ansible.builtin.git:
        repo: 'https://github.com/wlabra/devopspractice.git'
        dest: "/home/{{ ansible_user }}/devopspractice"
        version: main
        force: true
        accept_hostkey: true
      become: yes
      become_user: "{{ ansible_user }}"

    - name: Personalizar index.html según el servidor
      ansible.builtin.copy:
        content: "<h1>Hola desde el {{ inventory_hostname }}</h1>"
        dest: "/home/{{ ansible_user }}/devopspractice/index.html"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0644'

    - name: Levantar la infraestructura con Docker Compose
      community.docker.docker_compose_v2:
        project_src: "/home/{{ ansible_user }}/devopspractice"
        state: present
        recreate: always